### ISSUE TITLE
where is requirements.txt?

### ISSUE THREAD

**Issue by Arthur-Ling** [MarsJacobs/ti-kd-qat#2]
I can not find any requirements.txt in the main branch, where is it?

**Comment by MarsJacobs** [comment]
Thank you for showing interest in the code implementation. My apologies for overlooking the addition of `requirements.txt`. This code implementation does not utilize the Huggingface Transformer package. Instead, it directly uses the code in the transformer folder. Therefore, you would only need basic package imports, including PyTorch. 

If you still face import errors after installing the packages I've listed, you can further install the necessary packages using `pip install`.

- torch, scipy, requests, tqdm, numpy, scipy, sklearn
